### ISSUE TITLE
release plan robot not working

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/published-documentation#114]
https://github.com/nih-cfde/published-documentation/runs/1380168249?check_suite_focus=true

I didn't read through the whole output, but I would not be surprised if this is also related to the specifications-and-documentation repo being private.

**Comment by s-canchi** [comment]
I think the first run was not run because the code didn't exist in one of the branches, but ran without issues the second time. The expected draft is also generated. You can check under the `Releases` tab on the main repo page to get a sense of what it might look like. Note that the label `proposedspecsupdate` didn't exist in the repo and I created it yesterday. If we want to retrospectively add this labels to the appropriate PRs, it will show up in the draft when a new PR is merged into either `dev` or `stable`.

**Comment by ACharbonneau** [comment]
cool
