### ISSUE TITLE
Clarify how C2M2 uses protected data

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/published-documentation#176]
we need to make sure to tell the DCCs that anything they submit will be publicly viewable and caution them not to include any protected data. Hopefully they already know and understand that - but just to be sure.

update in wiki.

@abradyIGS do you/should you talk about this in the main docs as well?

**Comment by lliming** [comment]
I don't think this is a portal or submission system feature, is it? There's nothing in the portal or submission system that talks about protected data or what should/should not be included in C2M2 submissions, is there? Is it the case that the content you're referring to would be in the published documentation site or something else other than the portal? 

If true, I don't think this shouldn't be tagged as part of the March Data Release epic, since it can be done at any time.

**Comment by ACharbonneau** [comment]
Hmm. We should hammer out exactly how we want to use epics. It sounds like what you want is an epic for 'only things that are explicitly part of the portal release' but the March Data Release is really a bunch of different aspects of the project that all need to come together at the same time. The portal per se needs to be released in conjunction with the docs, in conjunction with the updated public website, in conjunction with the newly rolled catalog, etc etc. Only a tiny fraction of the work is "coding updates in the portal", but I need to track all the pieces. Perhaps the 'portal per se' issues need to be their own sub-epic of this one, so you can just track those.

**Comment by ACharbonneau** [comment]
wiki is updated: 

> This portal supports faceted search of metadata concepts such as anatomical location, species, and assay type, across a wide variety of datasets using a controlled vocabulary (we currently do not have support for protected metadata terms).

**Comment by abradyIGS** [comment]
and the main doc says:

> *clinical observation metadata* and all other relevant *access-protected metadata*: CFDE-CC is currently soliciting concrete, detailed use case examples from DCCs so that we can establish realistic technical requirements
