### ISSUE TITLE
markdown tables not rendering 

### ISSUE THREAD

**Issue by raynamharris** [nih-cfde/published-documentation#345]
Some of the tables in the c2m2 technical docs are not rendering properly on the website, even though they look fine in github markdown. I'm guesses this is a problem with mkdocs.

https://docs.nih-cfde.org/en/latest/c2m2/draft-C2M2_specification/#c2m2-technical-specification
https://github.com/nih-cfde/c2m2/blob/master/draft-C2M2_specification/README.md

![Screen Shot 2022-04-04 at 3 28 10 PM](https://user-images.githubusercontent.com/7544197/161642243-e55b9004-c4dc-4c54-90fe-ce25fedb8a56.png)

![Screen Shot 2022-04-04 at 3 28 22 PM](https://user-images.githubusercontent.com/7544197/161642236-3f2f22ea-3fe4-4757-888e-b919b989377d.png)

**Comment by ACharbonneau** [comment]
RTD and mkdocs use different flavors of markdown than github. Github is more permissive about things like line returns and spaces. You'll need to fix the text to use official markdown rules rather than github flavor. Note that this is the C2M2 docs, so if you want it fixed, you need to put the issue in that repo where arthur will see it

**Comment by raynamharris** [comment]
thanks. see https://github.com/nih-cfde/c2m2/pull/65
